import Card from "./data/Card";
import Element from "./data/Element";

export default <Card[]>[
  {
    id: 1,
    name: "Geezard",
    ranks: { top: 1, left: 5, right: 4, bottom: 1 },
    element: null,
    level: 1,
  },
  {
    id: 2,
    name: "Funguar",
    ranks: { top: 5, left: 3, right: 1, bottom: 1 },
    element: null,
    level: 1,
  },
  {
    id: 3,
    name: "Bite Bug",
    ranks: { top: 1, left: 5, right: 3, bottom: 3 },
    element: null,
    level: 1,
  },
  {
    id: 4,
    name: "Red Bat",
    ranks: { top: 6, left: 2, right: 1, bottom: 1 },
    element: null,
    level: 1,
  },
  {
    id: 5,
    name: "Blobra",
    ranks: { top: 2, left: 5, right: 3, bottom: 1 },
    element: null,
    level: 1,
  },
  {
    id: 6,
    name: "Gayla",
    ranks: { top: 2, left: 4, right: 1, bottom: 4 },
    element: Element.THUNDER,
    level: 1,
  },
  {
    id: 7,
    name: "Gesper",
    ranks: { top: 1, left: 1, right: 5, bottom: 4 },
    element: null,
    level: 1,
  },
  {
    id: 8,
    name: "Fastitocalon-F",
    ranks: { top: 3, left: 1, right: 5, bottom: 2 },
    element: Element.EARTH,
    level: 1,
  },
  {
    id: 9,
    name: "Blood Soul",
    ranks: { top: 2, left: 1, right: 1, bottom: 6 },
    element: null,
    level: 1,
  },
  {
    id: 10,
    name: "Caterchipillar",
    ranks: { top: 4, left: 3, right: 2, bottom: 4 },
    element: null,
    level: 1,
  },
  {
    id: 11,
    name: "Cockatrice",
    ranks: { top: 2, left: 6, right: 1, bottom: 2 },
    element: Element.THUNDER,
    level: 1,
  },
  {
    id: 12,
    name: "Grat",
    ranks: { top: 7, left: 1, right: 1, bottom: 3 },
    element: null,
    level: 2,
  },
  {
    id: 13,
    name: "Buel",
    ranks: { top: 6, left: 3, right: 2, bottom: 2 },
    element: null,
    level: 2,
  },
  {
    id: 14,
    name: "Mesmerize",
    ranks: { top: 5, left: 4, right: 3, bottom: 3 },
    element: null,
    level: 2,
  },
  {
    id: 15,
    name: "Glacial Eye",
    ranks: { top: 6, left: 3, right: 1, bottom: 4 },
    element: Element.ICE,
    level: 2,
  },
  {
    id: 16,
    name: "Belhelmel",
    ranks: { top: 3, left: 3, right: 4, bottom: 5 },
    element: null,
    level: 2,
  },
  {
    id: 17,
    name: "Thrustaevis",
    ranks: { top: 5, left: 5, right: 3, bottom: 2 },
    element: Element.WIND,
    level: 2,
  },
  {
    id: 18,
    name: "Anacondaur",
    ranks: { top: 5, left: 5, right: 1, bottom: 3 },
    element: Element.POISON,
    level: 2,
  },
  {
    id: 19,
    name: "Creeps",
    ranks: { top: 5, left: 2, right: 2, bottom: 5 },
    element: Element.THUNDER,
    level: 2,
  },
  {
    id: 20,
    name: "Grendel",
    ranks: { top: 4, left: 2, right: 4, bottom: 5 },
    element: Element.THUNDER,
    level: 2,
  },
  {
    id: 21,
    name: "Jelleye",
    ranks: { top: 3, left: 7, right: 2, bottom: 1 },
    element: null,
    level: 2,
  },
  {
    id: 22,
    name: "Grand Mantis",
    ranks: { top: 5, left: 3, right: 2, bottom: 5 },
    element: null,
    level: 2,
  },
  {
    id: 23,
    name: "Forbidden",
    ranks: { top: 6, left: 2, right: 6, bottom: 3 },
    element: null,
    level: 3,
  },
  {
    id: 24,
    name: "Armadodo",
    ranks: { top: 6, left: 6, right: 3, bottom: 1 },
    element: Element.EARTH,
    level: 3,
  },
  {
    id: 25,
    name: "Tri-Face",
    ranks: { top: 3, left: 5, right: 5, bottom: 5 },
    element: Element.POISON,
    level: 3,
  },
  {
    id: 26,
    name: "Fastitocalon",
    ranks: { top: 7, left: 3, right: 5, bottom: 1 },
    element: Element.EARTH,
    level: 3,
  },
  {
    id: 27,
    name: "Snow Lion",
    ranks: { top: 7, left: 3, right: 1, bottom: 5 },
    element: Element.ICE,
    level: 3,
  },
  {
    id: 28,
    name: "Ochu",
    ranks: { top: 5, left: 3, right: 6, bottom: 3 },
    element: null,
    level: 3,
  },
  {
    id: 29,
    name: "SAM08G",
    ranks: { top: 5, left: 4, right: 6, bottom: 2 },
    element: Element.FIRE,
    level: 3,
  },
  {
    id: 30,
    name: "Death Claw",
    ranks: { top: 4, left: 2, right: 4, bottom: 7 },
    element: Element.FIRE,
    level: 3,
  },
  {
    id: 31,
    name: "Cactuar",
    ranks: { top: 6, left: 3, right: 2, bottom: 6 },
    element: null,
    level: 3,
  },
  {
    id: 32,
    name: "Tonberry",
    ranks: { top: 3, left: 4, right: 6, bottom: 4 },
    element: null,
    level: 3,
  },
  {
    id: 33,
    name: "Abyss Worm",
    ranks: { top: 7, left: 5, right: 2, bottom: 3 },
    element: Element.EARTH,
    level: 3,
  },
  {
    id: 34,
    name: "Turtapod",
    ranks: { top: 2, left: 7, right: 3, bottom: 6 },
    element: null,
    level: 4,
  },
  {
    id: 35,
    name: "Vysage",
    ranks: { top: 6, left: 5, right: 5, bottom: 4 },
    element: null,
    level: 4,
  },
  {
    id: 36,
    name: "T-Rexaur",
    ranks: { top: 4, left: 7, right: 6, bottom: 2 },
    element: null,
    level: 4,
  },
  {
    id: 37,
    name: "Bomb",
    ranks: { top: 2, left: 3, right: 7, bottom: 6 },
    element: Element.FIRE,
    level: 4,
  },
  {
    id: 38,
    name: "Blitz",
    ranks: { top: 1, left: 7, right: 6, bottom: 4 },
    element: Element.THUNDER,
    level: 4,
  },
  {
    id: 39,
    name: "Wendigo",
    ranks: { top: 7, left: 6, right: 3, bottom: 1 },
    element: null,
    level: 4,
  },
  {
    id: 40,
    name: "Torama",
    ranks: { top: 7, left: 4, right: 4, bottom: 4 },
    element: null,
    level: 4,
  },
  {
    id: 41,
    name: "Imp",
    ranks: { top: 3, left: 6, right: 7, bottom: 3 },
    element: null,
    level: 4,
  },
  {
    id: 42,
    name: "Blue Dragon",
    ranks: { top: 6, left: 3, right: 2, bottom: 7 },
    element: Element.POISON,
    level: 4,
  },
  {
    id: 43,
    name: "Adamantoise",
    ranks: { top: 4, left: 6, right: 5, bottom: 5 },
    element: Element.EARTH,
    level: 4,
  },
  {
    id: 44,
    name: "Hexadragon",
    ranks: { top: 7, left: 3, right: 5, bottom: 4 },
    element: Element.FIRE,
    level: 4,
  },
  {
    id: 45,
    name: "Iron Giant",
    ranks: { top: 6, left: 5, right: 5, bottom: 6 },
    element: null,
    level: 5,
  },
  {
    id: 46,
    name: "Behemoth",
    ranks: { top: 3, left: 7, right: 6, bottom: 5 },
    element: null,
    level: 5,
  },
  {
    id: 47,
    name: "Chimera",
    ranks: { top: 7, left: 3, right: 6, bottom: 5 },
    element: Element.WATER,
    level: 5,
  },
  {
    id: 48,
    name: "PuPu",
    ranks: { top: 3, left: 1, right: 10, bottom: 2 },
    element: null,
    level: 5,
  },
  {
    id: 49,
    name: "Elastoid",
    ranks: { top: 6, left: 7, right: 2, bottom: 6 },
    element: null,
    level: 5,
  },
  {
    id: 50,
    name: "GIM47N",
    ranks: { top: 5, left: 4, right: 5, bottom: 7 },
    element: null,
    level: 5,
  },
  {
    id: 51,
    name: "Malboro",
    ranks: { top: 7, left: 2, right: 7, bottom: 4 },
    element: Element.POISON,
    level: 5,
  },
  {
    id: 52,
    name: "Ruby Dragon",
    ranks: { top: 7, left: 4, right: 2, bottom: 7 },
    element: Element.FIRE,
    level: 5,
  },
  {
    id: 53,
    name: "Elnoyle",
    ranks: { top: 5, left: 6, right: 3, bottom: 7 },
    element: null,
    level: 5,
  },
  {
    id: 54,
    name: "Tonberry King",
    ranks: { top: 4, left: 4, right: 6, bottom: 7 },
    element: null,
    level: 5,
  },
  {
    id: 55,
    name: "Wedge, Biggs",
    ranks: { top: 6, left: 7, right: 6, bottom: 2 },
    element: null,
    level: 5,
  },
  {
    id: 56,
    name: "Fujin Raijin",
    ranks: { top: 2, left: 4, right: 8, bottom: 8 },
    element: null,
    level: 6,
  },
  {
    id: 57,
    name: "Elvoret",
    ranks: { top: 7, left: 4, right: 8, bottom: 3 },
    element: Element.WIND,
    level: 6,
  },
  {
    id: 58,
    name: "X-ATM092",
    ranks: { top: 4, left: 3, right: 8, bottom: 7 },
    element: null,
    level: 6,
  },
  {
    id: 59,
    name: "Granaldo",
    ranks: { top: 7, left: 5, right: 2, bottom: 8 },
    element: null,
    level: 6,
  },
  {
    id: 60,
    name: "Gerogero",
    ranks: { top: 1, left: 3, right: 8, bottom: 8 },
    element: Element.POISON,
    level: 6,
  },
  {
    id: 61,
    name: "Iguion",
    ranks: { top: 8, left: 2, right: 2, bottom: 8 },
    element: null,
    level: 6,
  },
  {
    id: 62,
    name: "Abadon",
    ranks: { top: 6, left: 5, right: 8, bottom: 4 },
    element: null,
    level: 6,
  },
  {
    id: 63,
    name: "Trauma",
    ranks: { top: 4, left: 6, right: 8, bottom: 5 },
    element: null,
    level: 6,
  },
  {
    id: 64,
    name: "Oilboyle",
    ranks: { top: 1, left: 8, right: 8, bottom: 4 },
    element: null,
    level: 6,
  },
  {
    id: 65,
    name: "Shumi",
    ranks: { top: 6, left: 4, right: 5, bottom: 8 },
    element: null,
    level: 6,
  },
  {
    id: 66,
    name: "Krysta",
    ranks: { top: 7, left: 1, right: 5, bottom: 8 },
    element: null,
    level: 6,
  },
  {
    id: 67,
    name: "Propagator",
    ranks: { top: 8, left: 8, right: 4, bottom: 4 },
    element: null,
    level: 7,
  },
  {
    id: 68,
    name: "Jumbo Cactuar",
    ranks: { top: 8, left: 4, right: 8, bottom: 4 },
    element: null,
    level: 7,
  },
  {
    id: 69,
    name: "Tri-Point",
    ranks: { top: 8, left: 8, right: 5, bottom: 2 },
    element: Element.THUNDER,
    level: 7,
  },
  {
    id: 70,
    name: "Gargantua",
    ranks: { top: 5, left: 8, right: 6, bottom: 6 },
    element: null,
    level: 7,
  },
  {
    id: 71,
    name: "Mobile Type 8",
    ranks: { top: 8, left: 3, right: 6, bottom: 7 },
    element: null,
    level: 7,
  },
  {
    id: 72,
    name: "Sphinxara",
    ranks: { top: 8, left: 8, right: 3, bottom: 5 },
    element: null,
    level: 7,
  },
  {
    id: 73,
    name: "Tiamat",
    ranks: { top: 8, left: 4, right: 8, bottom: 5 },
    element: null,
    level: 7,
  },
  {
    id: 74,
    name: "BGH251F2",
    ranks: { top: 5, left: 5, right: 7, bottom: 8 },
    element: null,
    level: 7,
  },
  {
    id: 75,
    name: "Red Giant",
    ranks: { top: 6, left: 7, right: 8, bottom: 4 },
    element: null,
    level: 7,
  },
  {
    id: 76,
    name: "Catoblepas",
    ranks: { top: 1, left: 7, right: 8, bottom: 7 },
    element: null,
    level: 7,
  },
  {
    id: 77,
    name: "Ultima Weapon",
    ranks: { top: 7, left: 8, right: 7, bottom: 2 },
    element: null,
    level: 7,
  },
  {
    id: 78,
    name: "Chubby Chocobo",
    ranks: { top: 4, left: 9, right: 4, bottom: 8 },
    element: null,
    level: 8,
  },
  {
    id: 79,
    name: "Angelo",
    ranks: { top: 9, left: 3, right: 6, bottom: 7 },
    element: null,
    level: 8,
  },
  {
    id: 80,
    name: "Gilgamesh",
    ranks: { top: 3, left: 6, right: 7, bottom: 9 },
    element: null,
    level: 8,
  },
  {
    id: 81,
    name: "MiniMog",
    ranks: { top: 9, left: 2, right: 3, bottom: 9 },
    element: null,
    level: 8,
  },
  {
    id: 82,
    name: "Chicobo",
    ranks: { top: 9, left: 4, right: 4, bottom: 8 },
    element: null,
    level: 8,
  },
  {
    id: 83,
    name: "Quezacotl",
    ranks: { top: 2, left: 4, right: 9, bottom: 9 },
    element: Element.THUNDER,
    level: 8,
  },
  {
    id: 84,
    name: "Shiva",
    ranks: { top: 6, left: 9, right: 7, bottom: 4 },
    element: Element.ICE,
    level: 8,
  },
  {
    id: 85,
    name: "Ifrit",
    ranks: { top: 9, left: 8, right: 6, bottom: 2 },
    element: Element.FIRE,
    level: 8,
  },
  {
    id: 86,
    name: "Siren",
    ranks: { top: 8, left: 2, right: 9, bottom: 6 },
    element: null,
    level: 8,
  },
  {
    id: 87,
    name: "Sacred",
    ranks: { top: 5, left: 9, right: 1, bottom: 9 },
    element: Element.EARTH,
    level: 8,
  },
  {
    id: 88,
    name: "Minotaur",
    ranks: { top: 9, left: 9, right: 5, bottom: 2 },
    element: Element.EARTH,
    level: 8,
  },
  {
    id: 89,
    name: "Carbuncle",
    ranks: { top: 8, left: 4, right: 4, bottom: 10 },
    element: null,
    level: 9,
  },
  {
    id: 90,
    name: "Diablos",
    ranks: { top: 5, left: 3, right: 10, bottom: 8 },
    element: null,
    level: 9,
  },
  {
    id: 91,
    name: "Leviathan",
    ranks: { top: 7, left: 7, right: 10, bottom: 1 },
    element: Element.WATER,
    level: 9,
  },
  {
    id: 92,
    name: "Odin",
    ranks: { top: 8, left: 5, right: 10, bottom: 3 },
    element: null,
    level: 9,
  },
  {
    id: 93,
    name: "Pandemona",
    ranks: { top: 10, left: 7, right: 1, bottom: 7 },
    element: Element.WIND,
    level: 9,
  },
  {
    id: 94,
    name: "Cerberus",
    ranks: { top: 7, left: 10, right: 4, bottom: 6 },
    element: null,
    level: 9,
  },
  {
    id: 95,
    name: "Alexander",
    ranks: { top: 9, left: 2, right: 10, bottom: 4 },
    element: Element.HOLY,
    level: 9,
  },
  {
    id: 96,
    name: "Phoenix",
    ranks: { top: 7, left: 10, right: 2, bottom: 7 },
    element: Element.FIRE,
    level: 9,
  },
  {
    id: 97,
    name: "Bahamut",
    ranks: { top: 10, left: 6, right: 8, bottom: 2 },
    element: null,
    level: 9,
  },
  {
    id: 98,
    name: "Doomtrain",
    ranks: { top: 3, left: 10, right: 1, bottom: 10 },
    element: Element.POISON,
    level: 9,
  },
  {
    id: 99,
    name: "Eden",
    ranks: { top: 4, left: 10, right: 4, bottom: 9 },
    element: null,
    level: 9,
  },
  {
    id: 100,
    name: "Ward",
    ranks: { top: 10, left: 8, right: 7, bottom: 2 },
    element: null,
    level: 10,
  },
  {
    id: 101,
    name: "Kiros",
    ranks: { top: 6, left: 10, right: 7, bottom: 6 },
    element: null,
    level: 10,
  },
  {
    id: 102,
    name: "Laguna",
    ranks: { top: 5, left: 9, right: 10, bottom: 3 },
    element: null,
    level: 10,
  },
  {
    id: 103,
    name: "Selphie",
    ranks: { top: 10, left: 4, right: 8, bottom: 6 },
    element: null,
    level: 10,
  },
  {
    id: 104,
    name: "Quistis",
    ranks: { top: 9, left: 2, right: 6, bottom: 10 },
    element: null,
    level: 10,
  },
  {
    id: 105,
    name: "Irvine",
    ranks: { top: 2, left: 10, right: 6, bottom: 9 },
    element: null,
    level: 10,
  },
  {
    id: 106,
    name: "Zell",
    ranks: { top: 8, left: 6, right: 5, bottom: 10 },
    element: null,
    level: 10,
  },
  {
    id: 107,
    name: "Rinoa",
    ranks: { top: 4, left: 10, right: 10, bottom: 2 },
    element: null,
    level: 10,
  },
  {
    id: 108,
    name: "Edea",
    ranks: { top: 10, left: 3, right: 10, bottom: 3 },
    element: null,
    level: 10,
  },
  {
    id: 109,
    name: "Seifer",
    ranks: { top: 6, left: 4, right: 9, bottom: 10 },
    element: null,
    level: 10,
  },
  {
    id: 110,
    name: "Squall",
    ranks: { top: 10, left: 9, right: 4, bottom: 6 },
    element: null,
    level: 10,
  },
];
